config/routes.rb
Rails.application.routes.draw do


  root to: 'welcome#index'


  resources :users

  scope module: :pras_devise do
    resources :registrations, only: [:new, :create]
    resources :confirmations, only: [:new, :show]
    resources :sessions, only: [:new, :create, :destroy]
    resources :password_resets, only: [:new, :edit, :create, :update]
  end

  resources :sites do
    resources :discussions do
      resources :comments
    end
  end


  namespace :api do
    get 'discussion_likes_and_comments' => 'discussions#likes_and_comments'

    post 'discussion_like' => 'discussions#create_like'
    post 'discussion_comment' => 'discussions#create_comment'
  end


  # /pageLikesAndComments.js
  get '/pageLikesAndComments' => "embeds#page_likes_and_comments", as: :embed_page_likes_and_comments, format: true


end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :site, counter_cache: true
  has_many :comments, dependent: :destroy

  def self.by_url(url)
    uri = URI.parse(url)
    where(url: uri.path).first_or_create
  end

  def like!
    update(likes: (self.likes + 1))
  end
end

# == Schema Information
#
# Table name: discussions
#
#  id             :bigint           not null, primary key
#  comments_count :integer          default(0)
#  likes          :integer          default(0)
#  url            :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  site_id        :bigint           not null
#
# Indexes
#
#  index_discussions_on_site_id          (site_id)
#  index_discussions_on_site_id_and_url  (site_id,url) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (site_id => sites.id)
#

app/controllers/api/discussions_controller.rb
class Api::DiscussionsController < ApiController

  before_action :set_site
  before_action :set_discussion

  def show
    render json: { likes: discussion.likes }
  end

  def create
  end

  def likes_and_comments
    render json: { likes: @discussion.likes, comments: @discussion.comments }
  end

  def create_like
    @discussion.like!
    render json: { likes: @discussion.likes }
  end

  def create_comment
    user_ip = request.env['REMOTE_ADDR']
    user_agent = request.env['HTTP_USER_AGENT']
    referrer = request.env['HTTP_REFERER']
    name = params[:comment][:author_name]
    email = params[:comment][:email]
    body = params[:comment][:body]

    comment_info = {
      blog: @site.domain,
      user_ip: user_ip,
      user_agent: user_agent,
      referrer: referrer,
      comment_author: name,
      comment_author_email: email,
      comment_content: body,
    }

    comment = if SpamChecker.new(comment_info).spam?
                 nil
               else
                 @discussion.comments.create(
                   site: @site,
                   name: name,
                   email: email,
                   body: body,
                   ip_address: user_ip,
                   user_agent: user_agent,
                   referrer: referrer,
                 )
               end

    render json: { comment: comment }
  end

  private def set_site
    @site = Site.by_url(params[:url])
    if @site.nil?
      render json: { error: "Site has not been registered." }
    end
  end

  private def set_discussion
    @discussion = @site.discussions.by_url(params[:url])
  end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  before_action :authenticate_user!

  before_action :set_site
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = @site.discussions
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = @site.discussions.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = @site.discussions.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  
    def set_site
      @site = Site.find(params[:site_id])
    end

    def set_discussion
      @discussion = @site.discussions.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:url, :title, :comments_count, :site_id)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_with(model: discussion, local: true) do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
        <% discussion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :comments_count %>
    <%= form.number_field :comments_count %>
  </div>

  <div class="field">
    <%= form.label :site_id %>
    <%= form.text_field :site_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discussions</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Comments count</th>
      <th>Likes</th>
      <th>Site</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <%= @site.id %>
      <%= discussion.id %>
      <tr>
        <td><%= discussion.url %></td>
        <td><%= discussion.title %></td>
        <td><%= discussion.comments_count %></td>
        <td><%= discussion.likes %></td>
        <td><%= discussion.site_id %></td>
        <td><%= link_to 'Show', site_discussion_path(@site, discussion) %></td>
        <td><%= link_to 'Edit', edit_site_discussion_path(@site, discussion) %></td>
        <td><%= link_to 'Destroy', site_discussion_path(@site, discussion), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discussion', new_site_discussion_path(@site) %>

app/views/discussions/new.html.erb
<h1>New Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @discussion.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @discussion.title %>
</p>

<p>
  <strong>Comments count:</strong>
  <%= @discussion.comments_count %>
</p>

<p>
  <strong>Likes</strong>
  <%= @discussion.likes %>
</p>

<p>
  <strong>Site:</strong>
  <%= @discussion.site_id %>
</p>

<table>
  <thead>
    <tr>
      <th>Author Name</th>
      <th>Author Email</th>
      <th>Body</th>
      <th>Ip address</th>
      <th>User agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussion.comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.email %></td>
        <td><%= comment.body %></td>
        <td><%= comment.ip_address %></td>
        <td><%= comment.user_agent %></td>
        <td><%= link_to 'Show', site_discussion_comment_path(@site, @discussion, comment) %></td>
        <td><%= link_to 'Edit', edit_site_discussion_comment_path(@site, @discussion, comment) %></td>
        <td><%= link_to 'Destroy', site_discussion_comment_path(@site, @discussion, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Comments path', site_discussion_comments_path(@site, @discussion) %> |
<%= link_to 'Edit', edit_site_discussion_path(@site, @discussion) %> |
<%= link_to 'Back', site_discussions_path(@site) %>