config/routes.rb
Rails.application.routes.draw do


  root to: 'welcome#index'


  resources :users

  scope module: :pras_devise do
    resources :registrations, only: [:new, :create]
    resources :confirmations, only: [:new, :show]
    resources :sessions, only: [:new, :create, :destroy]
    resources :password_resets, only: [:new, :edit, :create, :update]
  end

  resources :sites do
    resources :discussions do
      resources :comments
    end
  end


  namespace :api do
    get 'discussion_likes_and_comments' => 'discussions#likes_and_comments'

    post 'discussion_like' => 'discussions#create_like'
    post 'discussion_comment' => 'discussions#create_comment'
  end


  # /pageLikesAndComments.js
  get '/pageLikesAndComments' => "embeds#page_likes_and_comments", as: :embed_page_likes_and_comments, format: true


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :site, counter_cache: true
  belongs_to :discussion, counter_cache: true
end

# == Schema Information
#
# Table name: comments
#
#  id            :bigint           not null, primary key
#  body          :text
#  email         :string
#  ip_address    :string
#  name          :string
#  referrer      :string
#  user_agent    :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  discussion_id :bigint           not null
#  site_id       :bigint           not null
#
# Indexes
#
#  index_comments_on_discussion_id  (discussion_id)
#  index_comments_on_site_id        (site_id)
#
# Foreign Keys
#
#  fk_rails_...  (discussion_id => discussions.id)
#  fk_rails_...  (site_id => sites.id)
#

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  before_action :set_site
  before_action :set_discussion
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = @discussion.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @discussion.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @discussion.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_site
      @site = Site.find(params[:site_id])
    end

    def set_discussion
      @discussion = @site.discussions.find(params[:discussion_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:discussion_id, :name, :email, :body, :ip_address, :user_agent)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :discussion_id %>
    <%= form.text_field :discussion_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :ip_address %>
    <%= form.text_field :ip_address %>
  </div>

  <div class="field">
    <%= form.label :user_agent %>
    <%= form.text_field :user_agent %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Discussion</th>
      <th>Name</th>
      <th>Email</th>
      <th>Body</th>
      <th>Ip address</th>
      <th>User agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.discussion_id %></td>
        <td><%= comment.name %></td>
        <td><%= comment.email %></td>
        <td><%= comment.body %></td>
        <td><%= comment.ip_address %></td>
        <td><%= comment.user_agent %></td>
        <td><%= link_to 'Show', site_discussion_comment_path(@site, @discussion, comment) %></td>
        <td><%= link_to 'Edit', edit_site_discussion_comment_path(@site, @discussion, comment) %></td>
        <td><%= link_to 'Destroy', site_discussion_comment_path(@site, @discussion, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_site_discussion_comment_path(@site, @discussion) %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Discussion:</strong>
  <%= @comment.discussion_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @comment.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @comment.ip_address %>
</p>

<p>
  <strong>User agent:</strong>
  <%= @comment.user_agent %>
</p>

<%= link_to 'Edit', edit_site_discussion_comment_path(@site, @discussion, @comment) %> |
<%= link_to 'Back', site_discussion_comments_path(@site, @discussion) %>