config/routes.rb
Rails.application.routes.draw do


  root to: 'welcome#index'


  resources :users

  scope module: :pras_devise do
    resources :registrations, only: [:new, :create]
    resources :confirmations, only: [:new, :show]
    resources :sessions, only: [:new, :create, :destroy]
    resources :password_resets, only: [:new, :edit, :create, :update]
  end

  resources :sites do
    resources :discussions do
      resources :comments
    end
  end


  namespace :api do
    get 'discussion_likes_and_comments' => 'discussions#likes_and_comments'

    post 'discussion_like' => 'discussions#create_like'
    post 'discussion_comment' => 'discussions#create_comment'
  end


  # /pageLikesAndComments.js
  get '/pageLikesAndComments' => "embeds#page_likes_and_comments", as: :embed_page_likes_and_comments, format: true


end

app/models/site.rb
class Site < ApplicationRecord
  has_many :discussions
  has_many :comments

  def self.by_url(url)
    uri = URI.parse(url)
    find_by(domain: "#{uri.host}:#{uri.port}")
  end
end

# == Schema Information
#
# Table name: sites
#
#  id                :bigint           not null, primary key
#  comments_count    :integer          default(0)
#  discussions_count :integer          default(0)
#  domain            :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_sites_on_domain  (domain) UNIQUE
#

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  before_action :authenticate_user!

  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:domain)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_with(model: site, local: true) do |form| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
        <% site.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :domain %>
    <%= form.text_field :domain %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Sites</h1>

<table>
  <thead>
    <tr>
      <th>Domain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.domain %></td>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Domain:</strong>
  <%= @site.domain %>
</p>

<p>
  <strong>Total Discussions:</strong>
  <%= @site.discussions.size %>
</p>

<p>
  <strong>Total Comments:</strong>
  <%= @site.comments.size %>
</p>

<div>
<h4>Get comments and likes for your site!</h4>
  <p>
  Copy and put this snippet in your site's html, just before the closing body tag.
  </p>
  <pre>
    <%= h %Q(<div id="page-likes-and-comments"></div>) %>
    &lt;script src="<%= embed_page_likes_and_comments_url(format: :js) %>"&gt;&lt;/script&gt;
  </pre>
</div>

<%= link_to 'Discussions path', site_discussions_path(@site) %> |
<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>