config/routes.rb
Rails.application.routes.draw do


  root to: 'welcome#index'


  resources :users

  scope module: :pras_devise do
    resources :registrations, only: [:new, :create]
    resources :confirmations, only: [:new, :show]
    resources :sessions, only: [:new, :create, :destroy]
    resources :password_resets, only: [:new, :edit, :create, :update]
  end

  resources :sites do
    resources :discussions do
      resources :comments
    end
  end


  namespace :api do
    get 'discussion_likes_and_comments' => 'discussions#likes_and_comments'

    post 'discussion_like' => 'discussions#create_like'
    post 'discussion_comment' => 'discussions#create_comment'
  end


  # /pageLikesAndComments.js
  get '/pageLikesAndComments' => "embeds#page_likes_and_comments", as: :embed_page_likes_and_comments, format: true


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>
<title>Meaningless</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body>

<header>
  <nav>
    <% if current_user %>
      <p>
        Logged in as <%= current_user.email %>
        |
        <%= link_to "Logout", session_path('wowThisCanBeAnythingBecauseTheDestroyActionDoesntUseThis'), method: :delete %>
      </p>
    <% else %>
      <p>
        <%= link_to "Sign Up", new_registration_path %>
        |
        <%= link_to "Log In", new_session_path %>
      </p>
    <% end %>
  </nav>

  <% flash.each do |name, msg| %>
    <%= tag.div msg, id: name %>
  <% end %>
</header>

<main>
<%= yield %>
</main>

<footer>
</footer>

</body>


</html>